AWSTemplateFormatVersion: '2010-09-09'
Description: 'Master stack: PathToMasterStackFile'
Parameters:
  ImageId:
    Description: Amazon image on which instance is based.
    Type: String
  KeyName: 
    Description: Key Name to enter ssh.
    Type: String
    Default: "RaoDemo"
  InstanceType:
    Description: Instance choose only from free t2.micro, t2.nano, t2.small, t1.micro
    Type: String
    AllowedValues:
    - t2.micro
    - t2.nano
    - t2.small
    - t1.micro
    Default: "t2.micro"
  GroupName:
    Description: Amazon image on which instance is based.
    Type: String
  GroupDescription:
    Description: Amazon image on which instance is based.
    Type: String
Resources:

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: !Ref GroupDescription
      GroupName: !Ref GroupName
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: "Name"
          Value: "RaoDemoSecurityGroup"

  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId:  !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !GetAtt MySecurityGroup.GroupId
      Tags:
        - Key: "Name"
          Value: "raodemo"
Outputs:
  DNSName: 
    Value : !GetAtt MyInstance.PublicDnsName
  PublicIp: 
    Value: !GetAtt MyInstance.PublicIp